DATALOADER:
  Train_Eval_Filename: 'FTE_NLP/data/raw_EDT/Event_detection/dev_test.json'
  Train_Eval_Split: [0.7, 0.3]
  Token_Max_Len: 512
  Mask_Prob: 0.1
  Train_Batch_Size: 64
  Eval_Batch_Size: 64

TRAIN_EVAL:
  Learning_Rate: 1e-05
  Num_Train_Epochs: 3
  Save_Check_Point_Model: 'FTE_NLP/experiments/model_bucket/domain_adaption/distilbert/'